feat(io): add function to save data to a json file
owid/data-utils-py pull request #18
Opened 2022-05-30 13:46 UTC by pabloarosado

Add function that simply saves data to a json file.

2022-05-30 16:29 UTC, Marigold approved these changes
Looks good (I might add support for dumping numpy datetime types in the future, then it's gonna be perfect)

2022-05-30 19:38 UTC, lucasrodes approved these changes

2022-05-30 19:53 UTC, lucasrodes requested changes
Nice! Could you add a test for the new function?

2022-06-03 07:27 UTC, pabloarosado commented
> Nice! Could you add a test for the new function?

Feel free to add it yourself. I don't know how/what to test here (the `load_json` does have some additional logic that requires tests).

2022-06-07 19:38 UTC, merged